
[training]
train_data_path = "/mnt/data_r60_1/adv_robust_project/DiffusionSVS/binarized_data/_binarize-PopCS/06-10-2026-20h22m59s/train.h5"
train_data_stats_path = "/mnt/data_r60_1/adv_robust_project/DiffusionSVS/binarized_data/_binarize-PopCS/06-10-2026-20h22m59s/train_stats.npz"
val_data_path = "/mnt/data_r60_1/adv_robust_project/DiffusionSVS/binarized_data/_binarize-PopCS/06-10-2026-20h22m59s/val.h5"
rng_seed = 21
batch_size = 3
effective_batch_size = 48 #64
grad_accum_steps = 1
training_steps = 160000

val_loss_interval = 100
val_steps = 8 #2
checkpoint_interval = 10000
save_dir = "/mnt/data_r60_1/adv_robust_project/DiffusionSVS/experiments"

AdamW_weight_decay = 0.1 # idk
AdamW_betas = [0.9, 0.999] # idk
AdamW_epsilon = 1e-8 # idk

warmup_steps = 2000 # idk
max_lr = 2.5e-3 # idk, based off plot
min_lr = 3.5e-4 # idk, based off plot

ema_decay = 0

[training.diffusion]
beta_min = 1e-4
beta_max = 0.06
T = 100
k = 100 # the intersection point used in Algorithm 1 of DiffSinger, could use e.g. k=40 or try predicting k

[training.loss]
l1_weight = 1

[model]
model_type = "EncoderDecoder"

pad_token_id = 0 # maybe add a sanity check in training code that it matches with the vocab.json from the dataset that you end up loading
vocab_size = 60

dilation_cycle_length = 4 # for wavenet
num_wavenet_layers = 20
sinusoidal_base = 10000

num_mel_bins = 80
embedding_dim = 256

num_blocks = 6 # for decoder and encoder I guess
num_attention_heads = 2 # yes, this is what they used
max_seq_len = 32768
rotary_base = 10000

dropout = 0.1
