# default config for binarizing PopCS data

[audio]
sample_rate = 24000
hop_size = 128
window_size = 512
n_mels = 80
min_freq = 30 # Hz
max_freq = 12000 # Hz
mel_center = true # default in librosa
mel_log_clip = 1e-6

[f0]
extractor = "parselmouth"   # "parselmouth" | "harvest"
f0_min    = 50.0
f0_max    = 1100.0

[data]
save_dir = "/home/phil/DiffusionSVS/binarized_data"
min_sec = 2.5
max_sec = 15

ALEX_FLOAREA_AI_SVS_path = "/home/phil/DiffusionSVS/data/AlexFloarea-AI-SVS-main/AlexFloarea-AI-SVS-main"
ALEX_FLOAREA_EN_PUBLIC_path = "/home/phil/DiffusionSVS/data/Alex_Floarea_EN_Public_Corpus"
PROJECT_AIDOL_PUBLIC_ENGLISH_path = "/home/phil/DiffusionSVS/data/Project-AIdol-Public-English-Dataset-master/Project-AIdol-Public-English-Dataset-master"
NGYY_path = "/home/phil/DiffusionSVS/data/NGYY_ENG_Dataset-main/NGYY_ENG_Dataset-main"
OPEN_CPOP_path = "/home/phil/DiffusionSVS/data/opencpop"
M4SINGER_path = "/home/phil/DiffusionSVS/data/m4singer/m4singer"
NO7SINGING_path = "/home/phil/DiffusionSVS/data/no7singing"
RITSU_path = "/home/phil/DiffusionSVS/data/ritsu/「波音リツ」歌声データベースVer2.0.2"
POPCS_path = "/home/phil/DiffusionSVS/data/popcs"
SUNG_AND_SPOKEN_path = "/home/phil/DiffusionSVS/data/sungandspoken"
GTSINGER_ENGLISH_path = "/home/phil/DiffusionSVS/data/gtsinger/English-005/English"
GTSINGER_CHINESE_path = "/home/phil/DiffusionSVS/data/gtsinger/Chinese-006/Chinese"
GTSINGER_JAPANESE_path = "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese"
AMABOSHI_CIPHERDB_path = "/home/phil/DiffusionSVS/data/Amaboshi_CipherDB2改"
KUROTAKE_KOUGA_AI_SONG_path = "/home/phil/DiffusionSVS/data/Kurotake_Kouga_AI_Song"
OFUTON_P_UTAGOE_DB_path = "/home/phil/DiffusionSVS/data/OFUTON_P_UTAGOE_DB"
ONIKU_KURUMI_UTAGOE_DB_path = "/home/phil/DiffusionSVS/data/ONIKU_KURUMI_UTAGOE_DB"
PJS_CORPUS_path = "/home/phil/DiffusionSVS/data/PJS_corpus_ver1.1"
ENUNU_KODOKU_path = "/home/phil/DiffusionSVS/data/enunu_kodoku_database"
ITAKO_SINGING_path = "/home/phil/DiffusionSVS/data/itako_singing"
NIT070_DB_path = "/home/phil/DiffusionSVS/data/Nit070"
TIGER_EN_path = "/home/phil/DiffusionSVS/data/tiger_en"
TIGER_JP_path = "/home/phil/DiffusionSVS/data/tiger_jp"


test_paths = [
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0000_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0001_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0002_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0003_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0004_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0005_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0006_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0007_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0008_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0009_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0010_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0011_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0012_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0013_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0014_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-说散就散/0015_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0000_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0001_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0002_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0003_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0004_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0005_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0006_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0007_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0008_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0009_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-隐形的翅膀/0010_wf0.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Pharyngeal/You Raise Me Up/Pharyngeal_Group/0000.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Pharyngeal/You Raise Me Up/Pharyngeal_Group/0001.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Pharyngeal/You Raise Me Up/Pharyngeal_Group/0002.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Pharyngeal/You Raise Me Up/Pharyngeal_Group/0003.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Pharyngeal/You Raise Me Up/Pharyngeal_Group/0004.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Pharyngeal/You Raise Me Up/Pharyngeal_Group/0005.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Pharyngeal/You Raise Me Up/Pharyngeal_Group/0006.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Pharyngeal/You Raise Me Up/Pharyngeal_Group/0007.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0000.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0001.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0002.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0003.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0004.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0005.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0006.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0007.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0008.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0009.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0010.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0011.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0012.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Tenor-1/Vibrato/You Belong With Me/Vibrato_Group/0013.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0000.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0001.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0002.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0003.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0004.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0005.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0006.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0007.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0008.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0009.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Pharyngeal/πüòπéôπü╗πéÜ/Pharyngeal_Group/0010.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Vibrato/πüòπéôπü╗πéÜ/Vibrato_Group/0000.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Vibrato/πüòπéôπü╗πéÜ/Vibrato_Group/0001.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Tenor-1/Vibrato/πüòπéôπü╗πéÜ/Vibrato_Group/0002.wav",
]

val_paths = [
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0000_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0001_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0002_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0003_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0004_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0005_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0006_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0007_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0008_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0009_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0010_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0011_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-夏天的风/0012_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0000_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0001_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0002_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0003_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0004_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0005_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0006_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0007_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0008_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0009_wf0.wav",
    "/home/phil/DiffusionSVS/data/popcs/popcs-稻香/0010_wf0.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0000.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0001.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0002.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0003.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0004.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0005.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0006.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0007.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0008.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0009.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0010.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0011.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0012.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0013.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0014.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0015.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-1/Glissando/trouble is a friend/Glissando_Group/0016.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Breathy/My Love/Breathy_Group/0000.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Breathy/My Love/Breathy_Group/0001.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Breathy/My Love/Breathy_Group/0002.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Breathy/My Love/Breathy_Group/0003.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Breathy/My Love/Breathy_Group/0004.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Breathy/My Love/Breathy_Group/0005.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Breathy/My Love/Breathy_Group/0006.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Breathy/My Love/Breathy_Group/0007.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/English-005/English/EN-Alto-2/Breathy/My Love/Breathy_Group/0008.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Glissando/Σ╜òΦë▓πüªπéÖπééπü¬πüäΦè▒/Glissando_Group/0000.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Glissando/Σ╜òΦë▓πüªπéÖπééπü¬πüäΦè▒/Glissando_Group/0001.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Glissando/Σ╜òΦë▓πüªπéÖπééπü¬πüäΦè▒/Glissando_Group/0002.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Glissando/Σ╜òΦë▓πüªπéÖπééπü¬πüäΦè▒/Glissando_Group/0003.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Glissando/Σ╜òΦë▓πüªπéÖπééπü¬πüäΦè▒/Glissando_Group/0004.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Glissando/Σ╜òΦë▓πüªπéÖπééπü¬πüäΦè▒/Glissando_Group/0005.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Glissando/Σ╜òΦë▓πüªπéÖπééπü¬πüäΦè▒/Glissando_Group/0006.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Glissando/Σ╜òΦë▓πüªπéÖπééπü¬πüäΦè▒/Glissando_Group/0007.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0000.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0001.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0002.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0003.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0004.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0005.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0006.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0007.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0008.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0009.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0010.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0011.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0012.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0013.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0014.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0015.wav",
    "/home/phil/DiffusionSVS/data/gtsinger/Japanese-008/Japanese/JA-Soprano-1/Mixed_Voice_and_Falsetto/Φíîπüïπü¬πüäπüªπéÖ/Falsetto_Group/0016.wav",
]