
[training]
data_dir = "/mnt/data_r60_1/adv_robust_project/DiffusionSVS/binarized_data/_binarize-popcs-m4singer-gtsinger/07-14-2026-15h57m47s"
rng_seed = 21 #42#21
batch_size = 3 #24 # 3
effective_batch_size = 48
grad_accum_steps = 1 #2
training_steps = 160000 # 40000 # 160000
#resume_training = #true
#checkpoint_path = #"/mnt/data_r60_1/adv_robust_project/DiffusionSVS/experiments/_train-wavenet-denoiser/06-17-2026-07h53m58s/checkpoints/checkpoint_step100000.pt"
compute_dtype = "fp16"
use_torch_compile = false
torch_compile_dynamic = false

mel_pad_multiple = 1#2 #16 #4

val_loss_interval = 100
val_steps = 8
checkpoint_interval = 10000
save_dir = "/mnt/data_r60_1/adv_robust_project/DiffusionSVS/experiments"

use_muon = true

AdamW_base_lr = 1e-4
AdamW_weight_decay = 0.1
AdamW_betas = [0.9, 0.999]
AdamW_epsilon = 1e-8
Muon_base_lr = 0.02
Muon_weight_decay = 0.0
Muon_momentum = 0.95

null_embedding_base_lr = 1e-3 # uses AdamW
null_embedding_probability = 0.1

warmup_steps = 10000 #10000 # 5000 # 2000 # idk
cosine_decay_steps = 0 
min_lrm = 1

ema_decay = 0.9999 #0

[training.diffusion]
diffusion_type = "SimpleFlow"

[training.loss]
l2_weight = 1

[model]
model_type = "DiT"

use_cfg_null_embedding = true

patchify = false#true
patch_size = 1#2 #16 #4

pad_token_id = 0 # maybe add a sanity check in training code that it matches with the vocab.json from the dataset that you end up loading
vocab_size = 61

#dilation_cycle_length = 4 # for wavenet
#num_wavenet_layers = 20
sinusoidal_base = 10000

num_mel_bins = 80
embedding_dim = 256

num_blocks = 6 # for decoder and encoder I guess
num_dit_blocks = 6 #12 #6
num_attention_heads = 8 #2 # yes, 2 is what they used
max_phoneme_seq_len = 512
max_mel_frames = 8192
rotary_base = 10000

dropout = 0.1
